### ISSUE TITLE
Missing Prefab

### ISSUE THREAD

**Issue by iceleaf97** [keijiro/SkeletalGeometricEffects#3]
There is a "Missing Prefab" GameObject in Test scene.
I have already pulled the submodules.
I do not know how to solve this problem.

**Comment by keijiro** [comment]
Which GameObject is missing? A screen shot would be helpful.

**Comment by iceleaf97** [comment]
The unity version I used is 2018.1.1f1.
Now I open the scene with unity 2018.2.2f1 and there are all GameObjects in the scene.
The Missing Prefab is the GameObject "Neo".

**Comment by keijiro** [comment]
It seems you failed to clone the submodule `jp.keijiro.neolowman`. Is there any file in `Packages/jp.keijiro.neolowman`?

**Comment by iceleaf97** [comment]
Yes, there are some files in this folder.
[https://drive.google.com/open?id=1Z22hmRCHRvTVz4dColU9rv6WsUItQFam](url)

**Comment by iceleaf97** [comment]
[https://drive.google.com/open?id=1Z22hmRCHRvTVz4dColU9rv6WsUItQFam](url)
Yes, there are some files in this folder.

**Comment by iceleaf97** [comment]
Yes, there are some files in this folder.
https://drive.google.com/open?id=1Z22hmRCHRvTVz4dColU9rv6WsUItQFam

**Comment by keijiro** [comment]
Thanks for the info. Hmm, weird.

I'd recommend removing the project directory and staring over from `git clone --recursive`. If the issue still reproduces, please send me the project directory. I'll look into it.

**Comment by keijiro** [comment]
I'm closing this issue. Please feel free to reopen for further questions.
